version: "3"

volumes:
  prometheus-data:
    external: true

services:
  prometheus:
    image: prom/prometheus:v2.44.0
    restart: always
    ports:
      - 9090:9090
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    extra_hosts:
    - "host.docker.internal:host-gateway"
    command:
      - --storage.tsdb.retention.time=90d
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
  speedtest:
    image: "billimek/prometheus-speedtest-exporter:latest"
    restart: always
    ports:
      - 9469:9469
    environment:
      - server_ids=23282,58159
  freebox:
    image: "saphoooo/freebox-exporter"
    restart: always
    command: -fiber
    ports:
      - 10001:10001
    environment:
      - HOME=token
    volumes:
      - ./freebox-token:/token
